Inicio creacion metodo crear y guardar orden
jleiva/develectronicos-cenfotec pull request #20
Opened 2017-12-03 23:23 UTC by tonydzc

2017-12-04 20:02 UTC, jleiva requested changes

2017-12-04 20:02 UTC, jleiva commented on src/main/java/com/cenfotec/develectronicos/controllers/OrdenController.java
> +			case 1:
no es mejor que tipo sea de tipo Enum?

2017-12-04 20:02 UTC, jleiva commented on src/main/java/com/cenfotec/develectronicos/controllers/OrdenController.java
> +	public Documento crearTipoOrden(int tipo, Orden ord) {
no deberia de ser una fabrica?

2017-12-06 03:25 UTC, Danils123 commented on src/main/java/com/cenfotec/develectronicos/controllers/OrdenController.java
> +	public Documento crearTipoOrden(int tipo, Orden ord) {
Si me pareceria mejor un enum para eso

2017-12-06 18:27 UTC, tonydzc commented on src/main/java/com/cenfotec/develectronicos/controllers/OrdenController.java
> +	public Documento crearTipoOrden(int tipo, Orden ord) {
Si todos estan manejando estas cosas con fabrica, si

2017-12-06 18:30 UTC, tonydzc commented on src/main/java/com/cenfotec/develectronicos/controllers/OrdenController.java
> +			case 1:
pues si podria ser mas claro para especificar que tipo de orden es la que necesito crear

2017-12-11 15:55 UTC, merged