Cambios en controllers
jleiva/develectronicos-cenfotec pull request #25
Opened 2017-12-14 06:21 UTC by leizar

2017-12-14 18:19 UTC, jleiva requested changes

2017-12-14 18:19 UTC, jleiva commented on src/main/java/com/cenfotec/develectronicos/controllers/OrdenController.java
>  import com.cenfotec.develectronicos.data.DocumentoDAO;
Todo lo veo bien. Creo que seria remover los comentarios, y que @tonydzc le de un ojo a este controller, solo para estar seguros que va a funcionar con las Ordenes de el.

2017-12-15 03:37 UTC, tonydzc commented
todo ok

2017-12-15 17:26 UTC, jleiva approved these changes

2017-12-15 17:26 UTC, merged