Tramite consulta inventario state
jleiva/develectronicos-cenfotec pull request #4
Opened 2017-11-28 03:18 UTC by Danils123

2017-11-28 03:43 UTC, tonydzc approved these changes
me parece está bien

2017-11-29 02:16 UTC, jleiva requested changes

2017-11-29 02:16 UTC, jleiva commented on src/main/java/com/cenfotec/develectronicos/entities/Tramite.java
> +	private Departamento dept;
esta propiedad no se usa en ningun lado en esta clase

2017-11-29 02:16 UTC, jleiva commented on src/main/java/com/cenfotec/develectronicos/entities/Tramite.java
> +	private void setDoc(Documento doc) {
en ningun lado se usa este setDoc

2017-11-29 02:16 UTC, jleiva commented on src/main/java/com/cenfotec/develectronicos/entities/Tramite.java
lo mejor es quitar estos metodos de una vez, ya sabemos que no son responsabilidad del tramite

2017-11-29 02:16 UTC, jleiva commented on src/main/java/com/cenfotec/develectronicos/entities/procedure/interfaces/StateConsultaInventario.java
> +	public void estadoActual();
este metodo estadoActual() esta como raro, porque estadoActual no es una accion, es un _estado_

2017-11-29 02:16 UTC, jleiva commented on src/main/java/com/cenfotec/develectronicos/entities/procedure/TramiteConsultaInventario.java
> +public class TramiteConsultaInventario extends Tramite {
el prefijo de **Tramite** al inicio de estas clases parece innecesario, porque ya estan en el paquete especifico.

2017-11-29 02:49 UTC, Danils123 commented on src/main/java/com/cenfotec/develectronicos/entities/Tramite.java
> +	private Departamento dept;
Se usara en las clases hijas

2017-12-01 05:40 UTC, jleiva requested changes

2017-12-01 05:40 UTC, jleiva commented on src/main/java/com/cenfotec/develectronicos/main/mainPruebas.java
> +		Documento doc = new Documento();
Con los ultimos cambios de @tonydzc no te va a funcionar

2017-12-02 03:15 UTC, closed without merging